language: python
python:
  - "2.7"
env:
  - DJANGO=1.7
services:
  - redis
install:
  # - pip install -q Django==$DJANGO --use-mirrors
  - sudo apt-get install flite
  - bash requirements/install.sh
  # - pip install pep8 --use-mirrors
  # - pip install https://github.com/dcramer/pyflakes/tarball/master
before_script:
  - cp install/conf/settings_travis.py newfies/newfies_dialer/settings_local.py
  #- "mysql -e 'create database newfies;'"
  #- "mysql -e 'create database newfies_test;'"
  # - "pep8 --exclude=migrations --ignore=E501,E225 newfies"
  # - pyflakes -x W newfies
script:
  - py.test newfies/appointment/tests.py --ds=newfies.newfies_dialer.settings_test
  # - python newfies/manage.py test -s -x --with-xtraceback --with-color
  #- python newfies/manage.py test --settings=settings_travis -s --with-progressive --ignore-files=api_tests.py
# whitelist
branches:
  only:
    - develop